### ISSUE TITLE
Setting JWT_VERIFY_EXPIRATION to false fails with UnboundLocalError

### ISSUE THREAD

**Issue by jimfulton** [mattupstate/flask-jwt#49]
Because result is only set in one branch in _default_decode_handler.

**Comment by mattupstate** [comment]
New version should fix this

**Comment by xiaw61** [comment]
It still doesn't work for me. 

Which commit did you try to fix the problem? thx

**Comment by xiaw61** [comment]
In current code, we don't use JWT_VERIFY_EXPIRATION to set the expiration, right?

**Comment by jimfulton** [comment]
Apologies for not finding time to check this yet. :(
